### ISSUE TITLE
[Transfering] Wrong Pokemon

### ISSUE THREAD

**Issue by Mquark** [Spegeli/Pokemon-Go-Rocket-API#44] opened 2016-07-24 10:39 UTC
Holy fucking shit, this Bot ignores my MinIV Settings and transfered 100% Pokemons!

**Comment by mbastias** [comment] 2016-07-24 10:42
Issue #39 has this issue already.

**Comment by Mquark** [comment] 2016-07-24 10:45
Read it, and I am just wtf.

Spegeli uses the exact same settings names but changes the logic behind it?
Because of him so many ppl will loose their pokemon...

I don't get what the problem is to make it like it was and how everyone things it is:
MinCP: NO POKEMON  WITH EQUAL/HIGHER CP WILL BE TRANSFERED
MinIV: NO POKEMON WITH EQUAL/HIGHER IV WILL BE TRANSFERED

Thats it ...

**Comment by mbastias** [comment] 2016-07-24 10:49
Yeah happened to me too. You can bypass but keeping few copies(the duplicates you set), with the PrioritizeIVoverCP set to true.

**Comment by Mquark** [comment] 2016-07-24 10:51
No I am just using another bot and waitin til Spegeli responds and if he wants to do something about it.
Otherwise this bot is not an option for me and like I said, it will ruin many ppls pokemons.

**Comment by CL24** [comment] 2016-07-24 11:02
"Because of him so many ppl will loose their pokemon...

I don't get what the problem is to make it like it was and how everyone thinks it is:"

Because of him so many ppl have their pokemon. Stop botting, go outside and play yourself ungrateful guy.

**Comment by Spegeli** [comment] 2016-07-24 11:11
Currently the Transfer Logic is:

Select all Pokemon which are not in Gym or marked as Favorite and CP < MinCP
Then checkse the NotToTransfer List.
then depending if prioritizeIVoverCP enabled or not it will do the order CP or IV
and at the end keep the X amount highest/best you set via _client.Settings.KeepMinDuplicatePokemon

**Comment by Mquark** [comment] 2016-07-24 11:17
> KeepMinIVPercentage is currently not implanted/working because he will keep the stupid stuff like pokemons with 10 CP.

Stupid stuff? IV is what matters and not the cp.

> It will only transfer 100% when you set the KeepMinDuplicatePokemon to 0. But then its your fail.
KeepMinDuplicatePokemon was never 0. I let it default on 1.

**Comment by Spegeli** [comment] 2016-07-24 11:25
aha so you want to keep 100000000000000000000 rattats with 10CP and evolve them ALL to 4000+ ?

When KeepMinDuplicatePokemon was not 0, it can't be possible that he transferd all.

**Closed** 2016-07-24 11:25 UTC
