### ISSUE TITLE
[ANNOUNCEMENT] @ALL USERS - READ THIS FIRST

### ISSUE THREAD

**Issue by Spegeli** [Spegeli/Pokemon-Go-Rocket-API#93] opened 2016-07-27 13:20 UTC
Hi @everyone,
here are some short news how the bot will process the next days:

- Currently it's not planned to merge/update to the new Necro Version, because it contains to garbage Codes. Instead i will stay on the old/current base of my Fork.
- Before i will add new Features, i will do improvements and fixes for the current Features/Code first. To get it fast and more stable.
- I will NOT add any new Features within the next days, so please stop making/asking any Feature Requests. You can make improvement Requests for existing Features but all other Tickets will be closed instant.
- A GUI or extern Settings XML File for easier handling is planned the next days.

**Comment by DragonStar01** [comment] 2016-07-27 13:26
Ok but can you quick fix Pokemon transfer issue ?

**Comment by Spegeli** [comment] 2016-07-27 13:27
There is no Pokemon Transfer issue.

**Comment by MatkeMatke** [comment] 2016-07-27 13:37
it doesn't transfer any pokemon, even the ones which are under the set cp or IV percentage value, just keeps absolutely everything

**Comment by Spegeli** [comment] 2016-07-27 13:41
This is absolutly NOT possible.

**Comment by DragonStar01** [comment] 2016-07-27 13:42
In my settings "NotTransferPokemonsThatCanEvolve" is set to "false" 
But still it doesn't transfer 
SS => http://prntscr.com/by6d94

**Comment by Spegeli** [comment] 2016-07-27 13:48
This is not possible. If NotTransferPokemonsThatCanEvolve is False, the Logic is the following:

Select all Pokemon which not in Gym or marked as Favorite and under MinCP.
Then checks if one of the selected if on NoTransfer List, when yes sort it out.

Then he checks if prioritizeIVoverCP enabled, when yes sort them by IV otherwise by CP.
And then keep X best amount you set via TransferPokemonKeepDuplicateAmount.

**Comment by TerraNash** [comment] 2016-07-27 14:13
Thank you very much for your work.

I too have been suffering from the full inventory issue myself, and did some research to solve it. 
Despite increasing the KeepCP to over 1500 and only 1 duplicate (Yes to transfer, no to keeptoevolve etc..) he still saves duplicate amount of some pokemons BELOW the 85%IV value/CP value. I even checked the IVs of my pokemons to make sure. 

What I noticed is that he keeps the following duplicates almost exclusively: Pansir, Spearow, Caterpie and Doduo; they're not in the NotTransferList either. Pansir is probably because of being a high CP bastard, but the rest are crap.

Thank you, I am attempting to re-install a fresh one and see if this persists. It only started happening with the usage of GPX.

**Comment by Spegeli** [comment] 2016-07-27 14:15
Maybe the IDs for these Pokemons are wrong. Will take a look later.

**Comment by TerraNash** [comment] 2016-07-27 14:24
Thank you very much, sir. 

I also want to update that after running a FRESH new install, with same settings as my previous one, the bot is actually transferring. Yes, it immediately identified that I had 100 pokemons to transfer.

As I thought; we, the users, might have screwed up something. 

You were correct, the problem is from our end. I **Suggest** that anyone whose having this issue to simply make a fresh new install.

Once again, thank you.

**Comment by Luc4z** [comment] 2016-07-27 16:04
no need for new features now , i don't know what else we need , but only thing is i wondering how to improve speed and decrease pokemon flee

**Comment by Spegeli** [comment] 2016-07-27 16:08
CatchFlee mostly happens when you soft-banned.

**Comment by XiCynx** [comment] 2016-07-27 17:00
Sounds good boss, your work is clearly the best and I plan to stick with you and assist in any way I can until the end.  :)

**Comment by PeterPlanlos** [comment] 2016-07-27 19:50
hi,
can both be true?
public bool UseTransferPokemonKeepAboveCP
public bool UseTransferPokemonKeepAboveIV

i wanna hold all pokemons over cp 1500 and all pokemons iv over 95%, should be possible now or?

**Comment by Spegeli** [comment] 2016-07-27 21:40
You can use one, both or nothing ^^

**Comment by PeterPlanlos** [comment] 2016-07-28 11:41
Nice :)

**Comment by cawet1st** [comment] 2016-07-28 13:36
the bot can't find any pokestop, helpp X_X

**Comment by Karan1610** [comment] 2016-07-28 14:39
I'm new to these bots. Could someone explain how to run this one?

**Closed** 2016-07-28 14:46 UTC
