### ISSUE TITLE
[ISSUE ACCEPTED] UseGPXPathing error

### ISSUE THREAD

**Issue by skupfer** [Spegeli/Pokemon-Go-Rocket-API#49] opened 2016-07-24 13:08 UTC
[15:06:56] ----------------------------
[15:06:56] (INFO) Loading File: "\Configs\PokemonsNotToTransfer.txt"
[15:06:56] (INFO) Loading File: "\Configs\PokemonsNotToCatch.txt"
[15:06:56] (INFO) Loading File: "\Configs\PokemonsToEvolve.txt"
[15:06:56] (INFO) Export all Pokemon to "\Export\PokeList.csv"
[15:06:57] Der Wert des Parameters muss zwischen -90,0 und 90,0 liegen.
Parametername: Latitude from System.Device
[15:06:57] (ERROR) Got an exception, trying automatic restart..

File in Console/bin/Debug/ as Necros Readme states. Removed metadata-segment.

**Comment by skupfer** [comment] 2016-07-24 13:53
Cannot find a reference to this "[15:06:57] Der Wert des Parameters muss zwischen -90,0 und 90,0 liegen.
Parametername: Latitude from System.Device" to find out how the error is being produced...

**Comment by skupfer** [comment] 2016-07-24 14:40
Problem is "." in GPX-File! Must be changed to "," ... I guess this is an OS-dependend issue?

**Comment by holyst4r** [comment] 2016-07-24 15:05
how to use gpx files?

**Comment by skupfer** [comment] 2016-07-24 15:11
UserSettings -> True -> Enter Name (with extention) -> Place it in Console/bin/Debug

Remove from <metadata> to </metadata> including the section tags.

**Comment by Spegeli** [comment] 2016-07-24 21:55
Will take a look later at this issue. Thx for report.

**Comment by TehChozinOne** [comment] 2016-07-24 22:56
Is the issue been rectified?

**Comment by Spegeli** [comment] 2016-07-25 03:10
GFXPathing should be fixed.
Please try the latest Version and let me know.

**Comment by TehChozinOne** [comment] 2016-07-25 07:08
On Wiki it says this..

"5. Save the .gpx wherever your .exe is"

Your git doesn't have ".exe"

What and where is this ".exe" that you refer to?

**Comment by Spegeli** [comment] 2016-07-27 13:43
The issue is that US needs commas and EU needs dots inside the GPX File.
I will add a auto converting to the code, so we dont have to change this manuell ^^

**Comment by Spegeli** [comment] 2016-07-27 15:35
Fixed with the last Release: https://github.com/Spegeli/Pokemon-Go-Rocket-API/commit/0a9cb0642de497fdee41fcf22ef1d1149a41d46b

**Closed** 2016-07-27 15:35 UTC
Labels: bug

**Comment by skupfer** [comment] 2016-07-27 15:55
I don't know whether you w will see this. I am in EU (ger with ger windows) and need commas in gpx and settings (during build)...
